#----- NetCore Plugin Config -----#

#Database-Settings. Available provider types: MySQL, MariaDB, SQLite, H2.
#Note: At this time, NetCore natively only comes with the MariaDB driver.
#If you intend to use other types, make sure the drivers are provided.
Database:
  provider: MariaDB
  host: localhost
  port: 3306
  database: minecraft
  username: minecraft
  password: password
  max-pool-size: 10
  connection-timeout: 5000
  database-directory: /plugins/NetCore/

#Redis-Settings. Make sure redis is configured right (protected mode, password), in order to avoid exploiting.
Redis:
  host: localhost
  port: 6379
  password: password
  database: 0
  max-pool-size: 1
  connection-timeout: 5000

#Note that the scoreboard is running on the subserver. The update-interval is measured in ticks.
#Compatible Unicodes: https://pastebin.com/nEPyiG65
#Small Font: https://lingojam.com/MinecraftSmallFont
#Papi Placeholders: https://github.com/PlaceholderAPI/PlaceholderAPI/wiki/Placeholders
#Example placeholder addons: LocalTime, LuckPerms, Player, Server
Scoreboard:
  enabled: true
  update-interval: 40 # Ticks
  title: "&b&lѕᴇʀᴠᴇʀ"
  playtime-format: "[%h% Hour(s) ]" #[%d% Day(s) ][%h% Hour(s) ][%m% Minute(s) ][%s% Second(s)]
  scores:
    - "&7&m                                "
    - "       &7%localtime_time_DD.MM.YY HH:mm%"
    - "&r"
    - "&b&l%player_name%"
    - "&8| &7ʀᴀɴᴋ&8: &r%luckperms_prefix%"
    - "&8| &7ᴘɪɴɢ&8: &r%player_colored_ping% &7ms"
    - "&8| &7ᴘʟᴀʏᴛɪᴍᴇ&8: &r%playtime%"
    - "&r"
    - "&b&lServer"
    - "&8| &7ɴᴀᴍᴇ&8: &7Server-1"
    - "&8| &7ᴏɴʟɪɴᴇ&8: &b%server_online%"
    - "&r"
    - "          &7ѕᴇʀᴠᴇʀ.ɴᴇᴛ"
    - "&7&m                                "

Tablist:
  enabled: true
  format: "%prefix% &8| &7%player_name% %suffix%"
  text:
    enabled: false  #Not yet implemented.
    header: ""
    footer: ""

Chat:
  enabled: true
  cooldown: 3 # Seconds
  anti-spam: true # Prevent sending the same message twice
  anti-caps: true # Prevent messages with > 50% caps
  format: "%prefix% &8| §7%player_name% §8» §7%message%" # Available placeholders: %prefix%, %player_name%, %message% + PAPI
  join-message: "&7[&b+&7] %player_name%"
  quit-message: "&7[&c-&7] %player_name%"
  blocked-commands:
    whitelist: true
    message: "&cYou are not permitted to use this command!"
    commands:
      - "plugins"
      - "version"

Users:
  cache-duration: 2880 #Minutes
  playtime-format: "[%d% Day(s) ][%h% Hour(s) ][%m% Minute(s) ][%s% Second(s) ]"



